from typing import Protocol

from src.main.api.models.base_model import BaseModel


class CrudEndpointInterface(Protocol):
    def post(self, model: BaseModel) -> BaseModel: ...
    def get(self, model: BaseModel | None = None, id: int | None = None) -> BaseModel: ...
    def update(self, model: BaseModel | None, id: int | None = None) -> BaseModel: ...
    def delete(self, id: int) -> BaseModel | bool: ...
