apiVersion: v1
kind: ConfigMap
metadata:
  name: nbank-backend-config
  namespace: {{ .Values.namespace.name }}
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nbank
  FRAUD_DETECTION_SERVICE_URL: {{ .Values.backend.env.fraudDetectionServiceUrl | quote }}